services:
  db:
    image: postgres:17
    container_name: db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      PORT: ${PORT}
      DSN: ${DSN}
      ORIGIN: ${ORIGIN}
      DIST_DIR: ${DIST_DIR}
      VITE_SERVER_URL: ${VITE_SERVER_URL}
      DEV: ${DEV}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./web/dist:/root/dist

volumes:
  postgres_data:
  minio_data:
