// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadAPI() {
  return window['go']['main']['App']['ReadAPI']();
}

export function UpdateAPI(arg1) {
  return window['go']['main']['App']['UpdateAPI'](arg1);
}
