// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadAPI():Promise<string>;

export function RunMakeBSD():Promise<void>;

export function UpdateAPI(arg1:string):Promise<void>;
