/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const LayoutRouteLazyImport = createFileRoute('/_layout')()
const LayoutIndexLazyImport = createFileRoute('/_layout/')()
const LayoutDatabaseLazyImport = createFileRoute('/_layout/database')()

// Create/Update Routes

const LayoutRouteLazyRoute = LayoutRouteLazyImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/_layout/route.lazy').then((d) => d.Route))

const LayoutIndexLazyRoute = LayoutIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRouteLazyRoute,
} as any).lazy(() => import('./routes/_layout/index.lazy').then((d) => d.Route))

const LayoutDatabaseLazyRoute = LayoutDatabaseLazyImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => LayoutRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/_layout/database.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/_layout/database': {
      id: '/_layout/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof LayoutDatabaseLazyImport
      parentRoute: typeof LayoutRouteLazyImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexLazyImport
      parentRoute: typeof LayoutRouteLazyImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteLazyRouteChildren {
  LayoutDatabaseLazyRoute: typeof LayoutDatabaseLazyRoute
  LayoutIndexLazyRoute: typeof LayoutIndexLazyRoute
}

const LayoutRouteLazyRouteChildren: LayoutRouteLazyRouteChildren = {
  LayoutDatabaseLazyRoute: LayoutDatabaseLazyRoute,
  LayoutIndexLazyRoute: LayoutIndexLazyRoute,
}

const LayoutRouteLazyRouteWithChildren = LayoutRouteLazyRoute._addFileChildren(
  LayoutRouteLazyRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteLazyRouteWithChildren
  '/database': typeof LayoutDatabaseLazyRoute
  '/': typeof LayoutIndexLazyRoute
}

export interface FileRoutesByTo {
  '/database': typeof LayoutDatabaseLazyRoute
  '/': typeof LayoutIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteLazyRouteWithChildren
  '/_layout/database': typeof LayoutDatabaseLazyRoute
  '/_layout/': typeof LayoutIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/database' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/database' | '/'
  id: '__root__' | '/_layout' | '/_layout/database' | '/_layout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRouteLazyRoute: typeof LayoutRouteLazyRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteLazyRoute: LayoutRouteLazyRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout/route.lazy.tsx",
      "children": [
        "/_layout/database",
        "/_layout/"
      ]
    },
    "/_layout/database": {
      "filePath": "_layout/database.lazy.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.lazy.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
